# Generated by Django 6.0.5 on 2026-05-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermountainlog",
            name="flights_climbed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermountainlog",
            name="steps",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
