# Generated by Django 4.2.25 on 2026-05-31 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("progress", "0003_multiple_ascents_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermountainlog",
            name="is_route_primary",
            field=models.BooleanField(
                default=False,
                help_text="True for the highest peak on a multi-mountain route (stats stored here).",
            ),
        ),
        migrations.AddField(
            model_name="usermountainlog",
            name="route_group_id_ref",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Shared UUID across all logs created in the same route session.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RouteLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the route, e.g. 'Fairfield Horseshoe'",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional notes about the route."
                    ),
                ),
                ("completed_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="usermountainlog",
            name="route_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this log was created as part of a multi-mountain route.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mountain_logs",
                to="progress.routelog",
            ),
        ),
    ]
