# Generated by Django 4.2.25 on 2026-06-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0004_usermountainlog_is_route_primary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermountainlog",
            name="conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("clear", "Clear & sunny"),
                    ("good", "Good visibility"),
                    ("misty", "Misty / low cloud"),
                    ("rain", "Rain / wet"),
                    ("snow", "Snow / ice"),
                    ("winter", "Full winter conditions"),
                    ("storm", "Storm / poor conditions"),
                ],
                help_text="Weather/visibility conditions on the day of the ascent.",
                max_length=20,
            ),
        ),
    ]
