# Generated by Django 4.2.25 on 2026-06-01 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("progress", "0005_usermountainlog_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="routelog",
            name="status",
            field=models.CharField(
                choices=[("planned", "Planned"), ("completed", "Completed")],
                default="completed",
                help_text="Whether this route has been completed or is being planned.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="routelog",
            name="completed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="UserCollectionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection_id_ref",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="ID of the collection this note belongs to.",
                    ),
                ),
                (
                    "collection_slug",
                    models.CharField(
                        db_index=True,
                        help_text="Slug of the collection, for lookups without a join.",
                        max_length=120,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Personal note about progress on this collection.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "collection_id_ref")},
            },
        ),
    ]
