# Generated by Django 4.2.25 on 2026-06-04 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("progress", "0006_routelog_status_alter_routelog_completed_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_reminders_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Send email reminders for upcoming planned summits.",
                    ),
                ),
                (
                    "reminder_days_before",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="How many days before the planned date to send the reminder. Validated to be one of 1, 2, 3, or 7.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
