# Generated by Django 6.0.5 on 2026-05-19 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mountains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MountainCollectionMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank_in_collection",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mountain_memberships",
                        to="mountains.mountaincollection",
                    ),
                ),
                (
                    "mountain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_memberships",
                        to="mountains.mountain",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "collection__name",
                    "rank_in_collection",
                    "mountain__name",
                ],
                "unique_together": {("mountain", "collection")},
            },
        ),
    ]
